### ISSUE TITLE
I sent you a littel bug

### ISSUE THREAD

**Issue by lom123ga** [quochung-cyou/QLDT_Enhancer#1]
*** Một số môn không có giáo viên -> date = temp[4] : sinh lỗi

*** chỉnh CN = 0 theo method getDay()

***  Chỉnh time_start trong 1 ngày thành 7h -> ( j - 7 ) * 70

**Comment by quochung-cyou** [comment]
Maybe fixed with commit (https://github.com/quochung-cyou/QLDT_Enhancer/commit/8368f5d5ab7eee11a2c1a479d31aa114a73a96f1)
